spring.application.name=Purchase-Web-Application
server.port=8080
server.tomcat.max-http-form-post-size= 2MB
# logging
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.web=TRACE
spring.cloud.gateway.httpclient.connect-timeout=10000
spring.cloud.gateway.httpclient.response-timeout=30s

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/purchase
spring.datasource.username=postgres
spring.datasource.password=Cloud912345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jackson.deserialization.unwrap-root-value=false

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=noreplycloud9softtechnologies@gmail.com
spring.mail.password=mxbitbuduvbkpcvt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
